#pragma once

const int souvenirSeedLines = 120;
const char* souvenirSeedData[souvenirSeedLines] = {
    "INSERT INTO Souvenirs VALUES('TD Garden','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('TD Garden','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('TD Garden','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('TD Garden','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Barclays Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Barclays Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Barclays Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Barclays Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Madison Square Garden','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Madison Square Garden','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Madison Square Garden','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Madison Square Garden','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Wells Fargo Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Wells Fargo Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Wells Fargo Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Wells Fargo Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Scotiabank Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Scotiabank Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Scotiabank Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Scotiabank Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('United Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('United Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('United Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('United Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Quicken Loans Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Quicken Loans Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Quicken Loans Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Quicken Loans Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Little Caesars Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Littlesouvenir Caesars Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Little Caesars Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Little Caesars Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Bankers Life Fieldhouse','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Bankers Life Fieldhouse','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Bankers Life Fieldhouse','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Bankers Life Fieldhouse','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Fiserv Forum','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Fiserv Forum','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Fiserv Forum','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Fiserv Forum','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('State Farm Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('State Farm Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('State Farm Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('State Farm Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Spectrum Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Spectrum Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Spectrum Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Spectrum Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('American Airlines Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('American Airlines Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('American Airlines Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('American Airlines Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Amway Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Amway Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Amway Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Amway Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Capital One Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Capital One Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Capital One Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Capital One Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Pepsi Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Pepsi Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Pepsi Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Pepsi Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Target Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Target Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Target Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Target Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Chesapeake Energy Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Chesapeake Energy Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Chesapeake Energy Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Chesapeake Energy Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Moda Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Moda Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Moda Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Moda Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Vivint Smart Home Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Vivint Smart Home Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Vivint Smart Home Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Vivint Smart Home Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Oracle Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Oracle Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Oracle Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Oracle Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Staples Center (Clippers)','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Staples Center (Clippers)','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Staples Center (Clippers)','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Staples Center (Clippers)','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Staples Center (Lakers)','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Staples Center (Lakers)','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Staples Center (Lakers)','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Staples Center (Lakers)','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Talking Stick Resort Arena','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Talking Stick Resort Arena','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Talking Stick Resort Arena','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Talking Stick Resort Arena','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Golden 1 Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Golden 1 Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Golden 1 Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Golden 1 Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('American Airlines Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('American Airlines Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('American Airlines Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('American Airlines Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Toyota Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Toyota Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Toyota Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Toyota Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('FedExForum','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('FedExForum','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('FedExForum','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('FedExForum','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('Smoothie King Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('Smoothie King Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('Smoothie King Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('Smoothie King Center','Team jersey','$179.79');",
    "INSERT INTO Souvenirs VALUES('AT&T Center','Autographed Basketball','$49.99');",
    "INSERT INTO Souvenirs VALUES('AT&T Center','Team pennant','$17.99');",
    "INSERT INTO Souvenirs VALUES('AT&T Center','Team picture','$29.89');",
    "INSERT INTO Souvenirs VALUES('AT&T Center','Team jersey','$179.79');"
};

const int stadiumSeedLines = 30;
const char* stadiumSeedData[souvenirSeedLines] = {
    "INSERT INTO Stadiums VALUES('Eastern','Atlantic','Boston Celtics','Boston, Massachusetts','TD Garden',18624,'1946','Ime Udoka');",
    "INSERT INTO Stadiums VALUES('Eastern','Atlantic','Brooklyn Nets','New York City, New York','Barclays Center',17732,'1976','Steve Nash');",
    "INSERT INTO Stadiums VALUES('Eastern','Atlantic','New York Knicks','New York City, New York','Madison Square Garden',19812,'1946','Tom Thibodeau');",
    "INSERT INTO Stadiums VALUES('Eastern','Atlantic','Philadelphia 76ers','Philadelphia, Pennsylvania','Wells Fargo Center',21600,'1949','Doc Rivers');",
    "INSERT INTO Stadiums VALUES('Eastern','Atlantic','Toronto Raptors','Toronto, Ontario','Scotiabank Arena',19800,'1995','Nick Nurse');",
    "INSERT INTO Stadiums VALUES('Eastern','Central','Chicago Bulls','Chicago, Illinois','United Center',20917,'1966','Billy Donovan');",
    "INSERT INTO Stadiums VALUES('Eastern','Central','Cleveland Cavaliers','Cleveland, Ohio','Quicken Loans Arena',20562,'1970','Larry Drew');",
    "INSERT INTO Stadiums VALUES('Eastern','Central','Detroit Pistons','Detroit, Michigan','Little Caesars Arena',20491,'1948','Dwane Casey');",
    "INSERT INTO Stadiums VALUES('Eastern','Central','Indiana Pacers','Indianapolis, Indiana','Bankers Life Fieldhouse',17923,'1976','Rick Carlisle');",
    "INSERT INTO Stadiums VALUES('Eastern','Central','Milwaukee Bucks','Milwaukee, Wisconsin','Fiserv Forum',18717,'1968','Mike Budenholzer');",
    "INSERT INTO Stadiums VALUES('Eastern','Southeast','Atlanta Hawks','Atlanta, Georgia','State Farm Arena',15711,'1949','Nate McMillan');",
    "INSERT INTO Stadiums VALUES('Eastern','Southeast','Charlotte Hornets','Charlotte, North Carolina','Spectrum Center',19077,'1988','James Borrego');",
    "INSERT INTO Stadiums VALUES('Eastern','Southeast','Miami Heat','Miami, Florida','American Airlines Arena',19600,'1988','Erik Spoelstra');",
    "INSERT INTO Stadiums VALUES('Eastern','Southeast','Orlando Magic','Orlando, Florida','Amway Center',18846,'1989','Jamahl Mosley');",
    "INSERT INTO Stadiums VALUES('Eastern','Southeast','Washington Wizards','Washington, D.C.','Capital One Arena',20356,'1961','Wes Unseld Jr.');",
    "INSERT INTO Stadiums VALUES('Western','Northwest','Denver Nuggets','Denver, Colorado','Pepsi Center',19520,'1976','Michael Malone');",
    "INSERT INTO Stadiums VALUES('Western','Northwest','Minnesota Timberwolves','Minneapolis, Minnesota','Target Center',19356,'1989','Chris Finch');",
    "INSERT INTO Stadiums VALUES('Western','Northwest','Oklahoma City Thunder','Oklahoma City, Oklahoma','Chesapeake Energy Arena',18203,'1967','Billy Donovan');",
    "INSERT INTO Stadiums VALUES('Western','Northwest','Portland Trail Blazers','Portland, Oregon','Moda Center',19441,'1970','Chauncey Billups');",
    "INSERT INTO Stadiums VALUES('Western','Northwest','Utah Jazz','Salt Lake City, Utah','Vivint Smart Home Arena',19911,'1974','Quin Snyder');",
    "INSERT INTO Stadiums VALUES('Western','Pacific','Golden State Warriors','Oakland, California','Oracle Arena',19596,'1946','Steve Kerr');",
    "INSERT INTO Stadiums VALUES('Western','Pacific','Los Angeles Clippers','Los Angeles, California','Staples Center (Clippers)',19060,'1970','Tyronn Lue');",
    "INSERT INTO Stadiums VALUES('Western','Pacific','Los Angeles Lakers','Los Angeles, California','Staples Center (Lakers)',18997,'1948','Frank Vogel');",
    "INSERT INTO Stadiums VALUES('Western','Pacific','Phoenix Suns','Phoenix, Arizona','Talking Stick Resort Arena',18055,'1968','Monte Williams');",
    "INSERT INTO Stadiums VALUES('Western','Pacific','Sacramento Kings','Sacramento, California','Golden 1 Center',17500,'1948','Luke Walton');",
    "INSERT INTO Stadiums VALUES('Western','Southwest','Dallas Mavericks','Dallas, Texas','American Airlines Center',19200,'1980','Jason Kidd');",
    "INSERT INTO Stadiums VALUES('Western','Southwest','Houston Rockets','Houston, Texas','Toyota Center',18055,'1967','Stephen Silas');",
    "INSERT INTO Stadiums VALUES('Western','Southwest','Memphis Grizzlies','Memphis, Tennessee','FedExForum',18119,'1995','Taylor Jennings');",
    "INSERT INTO Stadiums VALUES('Western','Southwest','New Orleans Pelicans','New Orleans, Louisiana','Smoothie King Center',16867,'2002','Willie Green');",
    "INSERT INTO Stadiums VALUES('Western','Southwest','San Antonio Spurs','San Antonio, Texas','AT&T Center',18418,'1976','Gregg Popovich');"
};
