name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:rolling
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Update Ubuntu Linux and install requisite packages
        run: |
            apt -y update && \
            DEBIAN_FRONTEND=noninteractive \
            apt -y install \
            qtbase5-dev \
            qt5-qmake-bin \
            g++ \
            make \
            nodejs

      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Build Qmake project
        run: |
            mkdir build && cd build
            qmake -o Makefile ../*.pro
            make

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          path: build/Lets_Play_NBA_Basketball
